Adjust sendMessage signature to match latest
Chrome has adjusted this signature so when this is called with an extensionId this mock fails an error 

TypeError: cb is not a function